
- name: Abhängigkeiten installieren
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - dkms
    - build-essential
    - linux-headers-{{ansible_kernel}}
    - checkinstall
    - pkg-config
    - libnl-3-dev
    - libnl-genl-3-dev
  when: domaenenliste is defined 

- name: create directory for batman-adv
  file:
    name: /opt/batman-adv
    state: directory
  when: domaenenliste is defined

- name: get batman 
  get_url:
    url: "https://downloads.open-mesh.org/batman/releases/batman-adv-2017.4/batman-adv-2017.4.tar.gz"
    dest: /opt/batman-adv/batman-adv-2017.4.tar.gz
  register: getbatman
  when: domaenenliste is defined

- name: batman-Quellen und entpacken
  unarchive:
    src: /opt/batman-adv/batman-adv-2017.4.tar.gz
    dest: /usr/src
    remote_src: True
  when: 
    - domaenenliste is defined
    - getbatman.changed

- stat: 
    path: /lib/modules/{{ansible_kernel}}/updates/net/batman-adv/batman-adv.ko
  register: batman_adv_file
  when: domaenenliste is defined

- name: Batman bauen
  shell: "make && make install"
  args:
    chdir: /usr/src/batman-adv-2017.4
  when:
    - batman_adv_file.stat.exists == False
    - domaenenliste is defined

# batctl
- name: create directory for batctl
  file:
    name: /opt/batctl
    state: directory
  when: domaenenliste is defined

- name: get batctl
  get_url:
    url: "https://downloads.open-mesh.org/batman/releases/batman-adv-2017.4/batctl-2017.4.tar.gz"
    dest: /opt/batctl/batctl-2017.4.tar.gz
  register: getbatctl
  when: domaenenliste is defined

- name: batctl-Quellen und entpacken
  unarchive:
    src: /opt/batctl/batctl-2017.4.tar.gz
    dest: /usr/src
    remote_src: True
  when:
    - domaenenliste is defined
    - getbatctl.changed

- stat: path=/usr/local/sbin/batctl
  register: batctl
  when: domaenenliste is defined

- name: batctl Version prüfen
  shell: '{{batctl.stat.path}} -v | grep -oE "batctl [0-9]+\.[0-9]+"'
  when: 
    - domaenenliste is defined
    - batctl.stat.exists == True
  changed_when: False
  register: batctl_version
  check_mode: no

- name: batctl bauen
  shell: "make && checkinstall -y make install"
  args:
    chdir: /usr/src/batctl-2017.4
  when:
    - domaenenliste is defined
    - batctl.stat.exists == False or batctl_version.stdout_lines[0] != "batctl 2017.4"

# creating batman interface
- name: Create interfaces - batman file
  template: src="batman.j2" dest="/etc/network/interfaces.d/10_batman.cfg"
  notify:
    - restart networking
  when: domaenenliste is defined

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking
  when: domaenenliste is defined

- name: Routingtabelle 42 auch ffnet nennen
  lineinfile: dest="/etc/iproute2/rt_tables" line="42   ffnet"
  when: domaenenliste is defined

- name: Drei Sekunden nach Kernelpanik automatisch neu starten
  sysctl: name="kernel.panic" value=3 sysctl_set=yes state=present reload=yes
  when: domaenenliste is defined
