#- name: Get existing datasources 
#  uri:
#    url: 'https://{{inventory_hostname_short}}.{{freifunk.domain}}/grafana/api/datasources'
#    force_basic_auth: true
#    user: '{{grafana.admin_user}}'
#    password: '{{grafana.admin_password}}'
#    return_content: true
#  register: grafana_datasources_output
#
#- name: Create non existing datasources
#  register: grafana_datasources_create_output
#  uri:
#    url: 'https://{{inventory_hostname_short}}.{{freifunk.domain}}/grafana/api/datasources'
#    method: POST
#    body:
#      name: 'Graphite'
#      type: 'graphite'
#      url: 'https://127.0.0.1'
#      access: 'proxy' 
#      isDefault: true
#    force_basic_auth: true
#    user: '{{grafana.admin_user}}'
#    password: '{{grafana.admin_password}}'
#    status_code: 200
#    body_format: json
#  when: "'Graphite' not in grafana_datasources_output.content"

#- name: Get existing dashboards
#  uri:
#    url: 'https://{{inventory_hostname_short}}.{{freifunk.domain}}/grafana/api/search'
#    force_basic_auth: true
#    user: '{{grafana.admin_user}}'
#    password: '{{grafana.admin_password}}'
#    return_content: true
#  register: grafana_dashboards_output
#
#- name: Ausgabe
#  debug:
#    var: grafana_dashboards_output
#
#- name: Ausgabe
#  debug:
#    var: grafana_dashboards_output.json|default([])

- set_fact:
    myvar: "{{ { 'dashboard' : lookup('file','dashboards/multidom_gateway.json') | from_json } }}"

- name: Create non existing dashboards
  register: grafana_dashboards_create_output
  uri:
    url: 'https://{{inventory_hostname_short}}.{{freifunk.domain}}/grafana/api/dashboards/db'
    method: POST
    body: '{{ myvar|to_json }}'
#    body: "{{ lookup('file','{{ item }}') }}"
    force_basic_auth: true
    user: '{{grafana.admin_user}}'
    password: '{{grafana.admin_password}}'
#    status_code: 200
#  when: "'Graphite' not in grafana_datasources_output.content"
#  with_fileglob:
#    - "dashboards/*"

- name: Ausgabe
  debug:
    var: grafana_dashboards_create_output

#- name: Ausgabe
#  debug:
#    var: grafana_dashboards_create_output.json|default([])
