- name: add repo key for labs.consol repo
  apt_key:
    keyserver: keys.gnupg.net
    id: F8C1CA08A57B9ED7

- name: add labs.consol repo
  apt_repository:
    repo: "deb http://labs.consol.de/repo/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install OMD
  apt: 
    pkg: omd
    update_cache: yes
    state: installed

- name: Create OMD {{freifunk.kurzname}} site
  command: omd create {{freifunk.kurzname}}
  args:
    creates: /opt/omd/sites/{{freifunk.kurzname}}

- name: Stop OMD {{freifunk.kurzname}} site
  command: omd stop {{freifunk.kurzname}}
  ignore_errors: yes

- name: Transfer the OMD configscript
  template: 
    src: omd-configure.sh 
    dest: /root/omd-configure.sh
    mode: 0777

- name: Execute the OMD configscript
  command: sh omd-configure.sh

- name: Start OMD {{freifunk.kurzname}} site
  command: omd start {{freifunk.kurzname}}
  ignore_errors: yes

- name: Configure gateways
  template: 
    src: srv-gateways.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/srv-gateways.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure icinga
  template:
    src: srv-icinga.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/srv-icinga.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure templates
  template: 
    src: templates.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/templates.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure services
  template:
    src: services.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/services.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure Satellites
  template: 
    src: srv-satellites.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/srv-satellites.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure Hostgrous
  template:
    src: srv-hostgroups.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/srv-hostgroups.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure VIP Nodes
  template:
    src: vip-nodes.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/vip-nodes.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Configure NRPE version2 command
  template:
    src: command-nrpe2.conf
    dest: /opt/omd/sites/{{freifunk.kurzname}}/etc/command-nrpe2.conf
    owner: "{{freifunk.kurzname}}"
    group: "{{freifunk.kurzname}}"

- name: Clean localhost default config
  file:
    state: absent
    path: /omd/sites/{{freifunk.kurzname}}/etc/icinga2/conf.d/hosts.conf

- name: Make sure we can use htpasswd module
  package:
    name: python-passlib
    state: latest

- htpasswd:
    path: /opt/omd/sites/{{freifunk.kurzname}}/etc/htpasswd
    name: "{{ monitoring.icingaadmin }}"
    password: "{{ monitoring.icingaadminpw }}"
