---
- name: Install NRPE-Server
  package:
    name: nagios-nrpe-server
    state: latest

- name: Configure NRPE-Server
  template: "src=nrpe_local.cfg.j2 dest='/etc/nagios/nrpe_local.cfg' owner=root group=root"

- name: Install Nagios Plugins
  package:
    name: nagios-plugins-standard
    state: latest

- name: Install bc
  package:
    name: bc
    state: latest

- name: Install vnstat
  package:
    name: vnstat
    state: latest

- name: Install vnstati
  package:
    name: vnstati
    state: latest

- name: Install RAM check
  copy: "src=check_ram dest='/usr/lib/nagios/plugins/check_ram' owner=root group=root mode=a+x"

- name: Install bandwith check
  copy: "src=check_bandwidth dest='/usr/lib/nagios/plugins/check_bandwidth' owner=root group=root mode=a+x"

- name: Install check_eth
  copy: "src=check_eth dest='/usr/lib/nagios/plugins/check_eth' owner=root group=root mode=a+x"

- name: Install Speedtest
  package:
    name: speedtest-cli
    state: latest

- name: Install check_speedtest-cli plugin
  copy: src=check_speedtest-cli.sh dest=/usr/lib/nagios/plugins/check_speedtest-cli.sh owner=root group=root mode=a+x

- name: Install DHCP lease check
  copy: "src=check_active-leases dest='/usr/lib/nagios/plugins/check_active-leases' owner=root group=root mode=a+x"

- name: stop NRPE-Server
  service:
    name: nagios-nrpe-server
    state: stopped

- name: start NRPE-Server
  service:
    name: nagios-nrpe-server
    state: started


