---
# Role for configure bird and bird6 for our gateway servers.
- name: add key for bird repo
  apt_key: keyserver=keyserver.ubuntu.com id=AC0E47584A7A714D
  when: ansible_distribution == "Debian"

- name: add bird repo
  apt_repository:
    repo: "deb http://bird.network.cz/debian/ jessie main"
    state: present
  when: ansible_distribution == "Debian"

- name: install bird and other required packets
  apt:
    pkg: "{{item}}"
    update_cache: yes
    cache_valid_time: 1800
    state: installed
  with_items:
    - bird
    - bird6
    - ipcalc
  when: ansible_distribution == "Debian"

- name: install bird and other required packets
  apt:
    pkg: "{{item}}"
    update_cache: yes
    cache_valid_time: 1800
    state: installed
  with_items:
    - bird
    - ipcalc
  when: ansible_distribution == "Ubuntu"

- name: calculate more specific routes for DHCP pools
  shell: ipcalc {{ domaenenliste[item].dhcp_start }} - {{ domaenenliste[item].dhcp_ende}} | grep -v "deaggregate" | sed -e 's/\(^.*$\)/route \1 via "bat{{item}}";/g'
  check_mode: no
  changed_when: false
  register: more_specific_routes
  with_items: "{{domaenenliste | default([])}}"
  when: domaenenliste is defined
  tags: bird_debug

- name: configure bird.conf
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify:
    - configure bird
  tags: bird_debug

- name: configure bird6.conf
  template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
  notify:
    - configure bird6
  tags: bird_debug

- name: activate and start bird
  service: name=bird state=started enabled=yes

- name: activate and start bird6
  service: name=bird6 state=started enabled=yes
